### ISSUE TITLE
Allow other async runtimes such as async-std

### ISSUE THREAD

**Issue by A248** [NetrexMC/RakNet#26]
I'd like to use this library myself, but with async-std rather than Tokio -- my existing code is written against async-std.

Could async-std be supported by a feature flag? I am willing to create a PR if necessary

**Comment by Bavfalcon9** [comment]
If it can be done without changing the API or code clutter than sure.

**Comment by A248** [comment]
No, it can't be done without changing the API. The API directly links to tokio, hence why I suggested a feature flag.

I'm not sure what exactly would qualify as code clutter. It depends on how much reliance there is on tokio, and how much of that can be replaced by executor-agnostic async code.

Based on a search for `tokio` using Github's search feature, tokio is only used inside `server.rs`, which seems promising.

**Comment by A248** [comment]
To clarify: the API would change very little. Only the `start` method appears to be affected. Overall, there doesn't seem to be an undue reliance on tokio, which means it may be easy to add support for other runtimes.

**Comment by Bavfalcon9** [comment]
The only things that would need to be modified are the tokio tasks inside `server.rs` with the start method.

**Comment by Bavfalcon9** [comment]
> To clarify: the API would change very little. Only the start method appears to be affected. Overall, there doesn't seem to be an undue reliance on tokio, which means it may be easy to add support for other runtimes.

Feel free to make a PR. I'd like the external API to remain relatively the same.

**Comment by Bavfalcon9** [comment]
I'll be including this in the v2 rewrite, as it includes a lot of design improvements from `master`, I expect the rewrite to be done sometime this week.

**Comment by Bavfalcon9** [comment]
Okay, now that everything *to my knowledge* is 100% working, I will get started on this issue 😄
