### ISSUE TITLE
[QUESTION] RakNet Client

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [NetrexMC/RakNet#39]
**Issue / Question:**
Hello, I stumbled upon this project and was wondering if it supports creating a RakNet client or if it was only restricted to creating a server?

**Proposals / Details:**
None

**Comment by Bavfalcon9** [comment]
hi! I have plans to add support for this (`v3` branch), however at the moment it doesn't support clients.

This won't take to long to add, a lot of people have been requesting this so I guess I can go ahead and work on that.

**Comment by ATXLtheAxolotl** [comment]
Ah, thank you for the clarification.

**Comment by ATXLtheAxolotl** [comment]
Do you have a discord server for this project?

**Comment by Bavfalcon9** [comment]
https://discord.gg/y4aWA5MQxK
