### ISSUE TITLE
Cookie field

### ISSUE THREAD

**Issue by ismaileke** [NetrexMC/RakNet#66]
You need to update OpenConnReply1 and OpenConnReq2

look at the Cookie field

![image](https://github.com/user-attachments/assets/330160a9-c76e-497e-8c27-83379d7050e3)

**Comment by john-bv** [comment]
Is this confirmed via wireshark? I'll look into it, if so, I'm going to be gating this behind a flag.

**Comment by ismaileke** [comment]
> Is this confirmed via wireshark? I'll look into it, if so, I'm going to be gating this behind a flag.

https://github.com/CloudburstMC/Network/blob/7e85ea3a09bb3b27e91ff55105c6f89b8650c79d/transport-raknet/src/main/java/org/cloudburstmc/netty/handler/codec/raknet/client/RakClientOfflineHandler.java#L154

https://github.com/Sandertv/go-raknet/blob/master/internal/message/open_connection_request_2.go

https://wiki.vg/Raknet_Protocol
